version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/log:/var/log/nginx
      - /var/repos:/var/www/html:ro
    links:
      - php-fpm
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  php-fpm:
    image: php:8-fpm
    volumes:
      - /var/repos:/var/www/html:ro