services:
  web:
    image: nginx:latest
    ports:
      - '80:8080'
    volumes:
      - /var/repos:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - /var/repos:/var/www/html