version: '3'

services:
  web:
    image: nginx:1.24.0
    ports:
      - 80:80
      - 443:443
    restart: always # Per riavvio automatico in caso di crash
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro # configurazione di nginx
      - ./certbot/www:/var/www/certbot/:ro # path per la creazione dei certificati
      - ./certbot/conf/:/etc/nginx/ssl/:ro # path certificati
      - ./nginx/log/:/var/log/nginx:rw # log nginx
      - /var/repos:/var/www/html:ro # path repository
    links:
      - php-fpm
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/repos:/var/www/html:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf:ro
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Skumbagmeno2000
    volumes:
      - ./database:/docker-entrypoint-initdb.d # Per script di inizializzazione
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mariadb_data: